#pragma once

// Breakable Brick
#define ID_ANI_BREAKABLE_BRICK 102001

#define BREAKABLE_BRICK_BBOX_WIDTH 16
#define BREAKABLE_BRICK_BBOX_HEIGHT 16

#define BREAKABLE_BRICK_GRAVITY 0.002f
#define BREAKABLE_BRICK_SPEED 0.09f

#define BREAKABLE_BRICK_MAX_DEBRIS_BRICK 10
#define BREAKABLE_BRICK_MIN_DEBRIS_BRICK 2

#define BREAKABLE_BRICK_NONE 0
#define BREAKABLE_BRICK_COIN 1
#define BREAKABLE_BRICK_DEBRIS_BRICK 2
#define BREAKABLE_BRICK_BUTTON 3

#define BREAKABLE_BRICK_STATE_BREAK 100
#define	BREAKABLE_BRICK_STATE_BOUNCE 200
#define	BREAKABLE_BRICK_STATE_NORMAL 300
#define BREAKABLE_BRICK_STATE_DISAPPEAR 400

// Debris Brick
#define ID_ANI_DEBRIS_BRICK_SPLASING 102011

#define DEBRIS_BRICK_BBOX_WIDTH 8
#define DEBRIS_BRICK_BBOX_HEIGHT 8

#define DEBRIS_BRICK_STATE_SPLASHING 1000

#define DEBRIS_BRICK_TIME_SPLASHING	1000
#define DEBRIS_BRICK_MAX_SPEED 0.09f
#define DEBRIS_BRICK_MIN_SPEED 0.05f