#pragma once

#define ID_ANI_BREAKABLE_BRICK_BREAK 101001

#define BREAKABLE_BRICK_BBOX_WIDTH 16
#define BREAKABLE_BRICK_BBOX_HEIGHT 16

#define BREAKABLE_BRICK_GRAVITY 0.002f
#define QUESTION_BRICK_SPEED 0.09f