#pragma once

#define ID_ANI_HUD_BACKGROUND 103001
#define ID_ANI_HUD_ARROW 103002

#define ID_ANI_FULL_POWER 103050

#define HUD_BACKGROUND_BBOX_WIDTH 252
#define HUD_BACKGROUND_BBOX_HEIGHT 30

#define HUD_ARROW_BBOX_HEIGHT 8
#define HUD_ARROW_BBOX_WIDTH 8

#define HUD_FULL_POWER_HEIGHT 8
#define HUD_FULL_POWER_WIDTH 14

#define HUD_FULL_POWER_FLASHING_DURATION 100