#pragma once

#define PIPE_BBOX_WIDTH 32

#define PIPE_BBOX_HEIGHT_SHORT 32
#define PIPE_BBOX_HEIGHT_LONG 48

#define ERROR_DISTANCE_ENTER_PIPE 4

// state
#define PIPE_STATE_LONG	1
#define PIPE_STATE_SHORT 2

#define PIPE_PLANT_NOTHING 0
#define PIPE_PLANT_SHOOTER_RED 1
#define PIPE_PLANT_SHOOTER_GREEN 2
#define PIPE_PLANT_CARNIVOROUS 3

#define PIPE_DIRECTION_DOWN 1
#define PIPE_DIRECTION_UP 2

#define PIPE_COLOR_GREEN 1
#define PIPE_COLOR_BLACK 2

// animations
#define ID_ANI_PIPE_LONG_GREEN_UP 101001
#define ID_ANI_PIPE_SHORT_GREEN_UP 101002

#define ID_ANI_PIPE_SHORT_BLACK_DOWN 101011