#pragma once

#pragma region ANIMATION_ID

#define ID_ANI_QUESTION_BRICK 100001
#define ID_ANI_QUESTION_BRICK_DISABLED 100002

#pragma endregion

// appearances
#define QUESTION_BRICK_BBOX_WIDTH 16
#define QUESTION_BRICK_BBOX_HEIGHT 16

#define QUESTION_BRICK_GRAVITY 0.002f
#define QUESTION_BRICK_SPEED 0.09f

#define QUESTION_BRICK_MUSHROOM_LIFE_UP 3
#define QUESTION_BRICK_ITEM_SUPPORT 2
#define QUESTION_BRICK_COIN 1
#define QUESTION_BRICK_NONE 0

// states
#define QUESTION_BRICK_STATE_UNBOXING 100
#define QUESTION_BRICK_STATE_DISABLED 200