#pragma once

#define ID_ANI_COIN 300001

#define COIN_STATE_IDLE 0
#define COIN_STATE_JUMP_OUT_QUESTION_BRICK 1

#define COIN_BBOX_WIDTH 8
#define COIN_BBOX_HEIGHT 8

#define COIN_GRAVITY 0.003f
#define COIN_JUMP_OUT_QUESTION_BRICK_SPEED_Y 0.58f
