#pragma once
// configs
#define MUSHROOM_SPEED 0.06f
#define MUSHROOM_GRAVITY 0.0022f

#define MUSHROOM_BBOX_WIDTH 16
#define MUSHROOM_BBOX_HEIGHT 16

#define MUSHROOM_STATE_WALKING 100
#define MUSHROOM_STATE_OUTSIDE 200

#define MUSHROOM_RED 1
#define MUSHROOM_GREEN 2

#pragma region ANIMATION_ID_300000

#define ID_ANI_MUSHROOM_RED 301001
#define ID_ANI_MUSHROOM_GREEN 301002

#pragma endregion