#pragma once

#define ID_ANI_INTRO_CURTAIN 3000000

#define INTRO_CURTAIN_BBOX_WIDTH  16
#define INTRO_CURTAIN_BBOX_HEIGHT 16

#define INTRO_PLATFORM_BBOX_WIDTH 24
#define INTRO_PLATFORM_BBOX_HEIGHT 34