#pragma once
#define GROUND_Y 160.0f

#define	MARIO_LEVEL_SMALL	1
#define	MARIO_LEVEL_BIG		2

//appearances
#define MARIO_SMALL_BBOX_WIDTH  14
#define MARIO_SMALL_BBOX_HEIGHT 16
#define MARIO_BIG_BBOX_WIDTH  14
#define MARIO_BIG_BBOX_HEIGHT 28
#define MARIO_BIG_SITTING_BBOX_WIDTH  14
#define MARIO_BIG_SITTING_BBOX_HEIGHT 18

#define MARIO_SIT_HEIGHT_ADJUST ((MARIO_BIG_BBOX_HEIGHT-MARIO_BIG_SITTING_BBOX_HEIGHT)/2)

#define MARIO_UNTOUCHABLE_TIME 1000

#define MARIO_WALKING_SPEED		0.1f
#define MARIO_RUNNING_SPEED		0.2f

#define MARIO_ACCEL_WALK_X	0.0005f
#define MARIO_ACCEL_RUN_X	0.0007f

#define MARIO_JUMP_SPEED_Y		0.55f
#define MARIO_JUMP_RUN_SPEED_Y	0.6f

#define MARIO_GRAVITY			0.002f

#define MARIO_JUMP_DEFLECT_SPEED  0.45f

#define MARIO_STATE_IDLE			0
#define MARIO_STATE_DIE				-10

#define MARIO_STATE_WALKING_RIGHT	100
#define MARIO_STATE_WALKING_LEFT	-100

#define MARIO_STATE_RUNNING_RIGHT	200
#define MARIO_STATE_RUNNING_LEFT	-200

#define MARIO_STATE_JUMP			300
#define MARIO_STATE_RELEASE_JUMP    301

#define MARIO_STATE_SIT				400
#define MARIO_STATE_SIT_RELEASE		401

#define MARIO_STATE_HOLDING_KOOPA	500
#define MARIO_STATE_HOLDING_KOOPA_RELEASE	501

#define MARIO_STATE_UNTOUCHABLE 600

#pragma region ANIMATION_ID

#define ID_ANI_MARIO_IDLE_RIGHT 400
#define ID_ANI_MARIO_IDLE_LEFT 401

#define ID_ANI_MARIO_WALKING_RIGHT 500
#define ID_ANI_MARIO_WALKING_LEFT 501

#define ID_ANI_MARIO_RUNNING_RIGHT 600
#define ID_ANI_MARIO_RUNNING_LEFT 601

#define ID_ANI_MARIO_JUMP_WALK_RIGHT 700
#define ID_ANI_MARIO_JUMP_WALK_LEFT 701

#define ID_ANI_MARIO_JUMP_RUN_RIGHT 800
#define ID_ANI_MARIO_JUMP_RUN_LEFT 801

#define ID_ANI_MARIO_SIT_RIGHT 900
#define ID_ANI_MARIO_SIT_LEFT 901

#define ID_ANI_MARIO_BRACE_RIGHT 1000
#define ID_ANI_MARIO_BRACE_LEFT 1001

#define ID_ANI_MARIO_DIE 999

// SMALL MARIO
#define ID_ANI_MARIO_SMALL_IDLE_RIGHT 1100
#define ID_ANI_MARIO_SMALL_IDLE_LEFT 1102

#define ID_ANI_MARIO_SMALL_WALKING_RIGHT 1200
#define ID_ANI_MARIO_SMALL_WALKING_LEFT 1201

#define ID_ANI_MARIO_SMALL_RUNNING_RIGHT 1300
#define ID_ANI_MARIO_SMALL_RUNNING_LEFT 1301

#define ID_ANI_MARIO_SMALL_BRACE_RIGHT 1400
#define ID_ANI_MARIO_SMALL_BRACE_LEFT 1401

#define ID_ANI_MARIO_SMALL_JUMP_WALK_RIGHT 1500
#define ID_ANI_MARIO_SMALL_JUMP_WALK_LEFT 1501

#define ID_ANI_MARIO_SMALL_JUMP_RUN_RIGHT 1600
#define ID_ANI_MARIO_SMALL_JUMP_RUN_LEFT 1601

// appearcance change
#define ID_ANI_MARIO_IDLE_APPEARANCE_CHANGING_RIGHT 1700
#define ID_ANI_MARIO_IDLE_APPEARANCE_CHANGING_LEFT 1701

#define ID_ANI_MARIO_WALKING_APPEARANCE_CHANGING_RIGHT 1800
#define ID_ANI_MARIO_WALKING_APPEARANCE_CHANGING_LEFT 1801

#define ID_ANI_MARIO_RUNNING_APPEARANCE_CHANGING_RIGHT 1900
#define ID_ANI_MARIO_RUNNING_APPEARANCE_CHANGING_LEFT 1901

#define ID_ANI_MARIO_JUMP_WALK_APPEARANCE_CHANGING_RIGHT 2000
#define ID_ANI_MARIO_JUMP_WALK_APPEARANCE_CHANGING_LEFT 2001

#define ID_ANI_MARIO_JUMP_RUN_APPEARANCE_CHANGING_RIGHT 2100
#define ID_ANI_MARIO_JUMP_RUN_APPEARANCE_CHANGING_LEFT 2101

#define ID_ANI_MARIO_BRACE_APPEARANCE_CHANGING_RIGHT 2200
#define ID_ANI_MARIO_BRACE_APPEARANCE_CHANGING_LEFT 2201

#define ID_ANI_MARIO_SIT_APPEARANCE_CHANGING_RIGHT 2300
#define ID_ANI_MARIO_SIT_APPEARANCE_CHANGING_LEFT 2301

#pragma endregion
