#pragma once

// animations
#define ID_ANI_QUESTION_BRICK 100000
#define ID_ANI_QUESTION_BRICK_EMPTY 100001

// appearances
#define QUESTION_BRICK_BBOX_WIDTH 16
#define QUESTION_BRICK_BBOX_HEIGHT 16

#define QUESTION_BRICK_SPEED_DOWN 0.04f
#define QUESTION_BRICK_SPEED_UP 0.04f

#define QUESTION_BRICK_MAX_HEIGHT 10

#define QUESTION_BRICK_ITEM 2
#define QUESTION_BRICK_MUSHROOM_GREEN 3
#define QUESTION_BRICK_BUTTON 4
#define QUESTION_BRICK_COIN 1

#define QUESTION_BRICK_STATE_UP 100

#define ADJUST_UP_DOWN 13