#pragma once

#define GOOMBA_TIME_FOR_EACH_FLY 1000
#define GOOMBA_WALKING_SPEED 0.094f
#define GOOMBA_FLY_SPEED_Y 0.155f
#define GOOMBA_DIE_TIMEOUT 500

// appearances
#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 14
#define GOOMBA_BBOX_HEIGHT_DIE 7

#define GOOMBA_BBOX_WIDTH_FLY 18
#define GOOMBA_BBOX_HEIGHT_FLY 18

//types
#define GOOMBA_TYPE_NORMAL 0
#define GOOMBA_TYPE_FLY 1

//states
#define GOOMBA_STATE_WALKING 100
#define GOOMBA_STATE_DIE 200
#define GOOMBA_STATE_FLY 300

// animation
#define ID_ANI_GOOMBA_WALKING 600001
#define ID_ANI_GOOMBA_DIE 600002
#define ID_ANI_GOOMBA_FLY 600003
