#pragma once

#define GOOMBA_TIME_FOR_EACH_FLY 2000
#define GOOMBA_WALKING_SPEED 0.094f
#define GOOMBA_FLY_SPEED_Y 0.19f
#define GOOMBA_DIE_TIMEOUT 500

// appearances
#define GOOMBA_BBOX_WIDTH 16
#define GOOMBA_BBOX_HEIGHT 16
#define GOOMBA_BBOX_HEIGHT_DIE 8

#define GOOMBA_BBOX_WIDTH_FLY 18
#define GOOMBA_BBOX_HEIGHT_FLY 18

//types
#define GOOMBA_TYPE_NORMAL 0
#define GOOMBA_TYPE_FLY 1

// animation
#define ID_ANI_GOOMBA_WALKING 600001
#define ID_ANI_GOOMBA_DIE 600002
#define ID_ANI_GOOMBA_FLY 600003
