#pragma once

#define ID_ANI_HAMMER_MOVE_RIGHT 604001
#define ID_ANI_HAMMER_MOVE_LEFT 604002

#define HAMMER_MOVING_MAX_X 8
#define HAMMER_MOVING_MAX_Y 32

#define HAMMER_BBOX_WIDTH 16
#define HAMMER_BBOX_HEIGHT 16