#pragma once
//appearances
#define KOOPA_GREEN 1
#define KOOPA_RED 2

#define KOOPA_BBOX_WIDTH 16
#define KOOPA_BBOX_HEIGHT 26
#define KOOPA_BBOX_HEIGHT_DEFEND 16

#define KOOPA_WALKING_SPEED 0.04f
#define KOOPA_MAX_SPEED 0.5f
#define KOOPA_ACCELERATION_DEFLECT 0.0006f
#define KOOPA_SLIDING_ACCELERATION 0.0003f

#define KOOPA_DEFEND_TIMEOUT 8000
#define KOOPA_COMBACK_TIMEOUT 2000

#define KOOPA_STATE_WALKING 100
#define KOOPA_STATE_DEFEND 200
#define KOOPA_STATE_IS_KICKED 300
#define KOOPA_STATE_UPSIDE 400
#define KOOPA_STATE_JUMP 500
#define KOOPA_STATE_IS_HOLDING 600
#define KOOPA_STATE_DIE_UPSIDE 700
#define KOOPA_STATE_COMEBACK 800
#define KOOPA_STATE_FLY 900

// Animation Ids
#define ID_ANI_KOOPA_WALKING_RIGHT 601001
#define ID_ANI_KOOPA_WALKING_LEFT 601002
#define ID_ANI_KOOPA_DEFEND 601003
#define ID_ANI_KOOPA_IS_KICKED 601004
#define ID_ANI_KOOPA_COMEBACK 601005
