#pragma once

#define MONSTER_DISAPPEAR_TIME 500
#define MONSTER_REVIVE_TIME 5000

#define MONSTER_DIE_DEFLECT_SPEED 0.2f
#define MONSTER_WALKING_SPEED 0.056f
#define MONSTER_JUMP_SPEED_Y 0.5f
#define MONSTER_BE_HITTED_BY_MARIO_DEFLECT_SPEED 0.19f
#define MONSTER_BE_HITTED_BY_MARIO_DEFLECT_VX 0.05f

// this file conatains all the monster general configs
#define MONSTER_STATE_DIE -1000000
#define MONSTER_STATE_IDLE 0
#define MONSTER_STATE_WALKING_RIGHT 3
#define MONSTER_STATE_WALKING_LEFT -3
#define MONSTER_STATE_ATTACK 2
#define MONSTER_STATE_JUMP -4
#define MONSTER_STATE_FALL 4
#define MONSTER_STATE_DEFLECT 5
#define MONSTER_STATE_FLY_RIGHT 6
#define MONSTER_STATE_FLY_LEFT -6
#define MONSTER_STATE_BE_HITTED 7
