#pragma once
#define MONSTER_DISAPPEAR_TIME 600
#define MONSTER_DIE_DEFLECT_SPEED 0.2f
#define MONSTER_WALKING_SPEED 0.05f
#define MONSTER_JUMP_SPEED_Y 0.5f

// this file conatains all the monster general configs
#define MONSTER_STATE_DIE -1000000
#define MONSTER_STATE_IDLE 0
#define MONSTER_STATE_WALKING_RIGHT 1
#define MONSTER_STATE_WALKING_LEFT -1
#define MONSTER_STATE_ATTACK 2
#define MONSTER_STATE_JUMP -4
#define MONSTER_STATE_FALL 4
#define MONSTER_STATE_DEFLECT 5
