#pragma once

#define PLANT_SPEED_UP_DOWN 0.025f
#define DISTANCE_PIPE_LONG_SHORT 8

#define TIME_OUT_PIPE 5000
#define TIME_SHOOT_INTERVAl 100
#define TIME_DOWN_PIPE 3000

#define PLANT_SHOOT_RED 1
#define PLANT_SHOOT_GREEN 2
#define PLANT_NOT_SHOOT 3

#define PLANT_BBOX_WIDTH 12
#define PLANT_BBOX_HEIGHT_SMALL 24
#define PLANT_BBOX_HEIGHT 32

#define PLANT_STATE_UP 100
#define PLANT_STATE_DOWN 200
#define PLANT_STATE_DEATH 300

// ID ANI

#define ID_ANI_PLANT_LEFT_UNDER_NOT_SHOOT	301
#define ID_ANI_PLANT_LEFT_UNDER_SHOOT 302
#define ID_ANI_PLANT_LEFT_TOP_NOT_SHOOT 303
#define ID_ANI_PLANT_LEFT_TOP_SHOOT 304
#define ID_ANI_PLANT_RIGHT_UNDER_NOT_SHOOT	305
#define ID_ANI_PLANT_RIGHT_UNDER_SHOOT 306
#define ID_ANI_PLANT_RIGHT_TOP_NOT_SHOOT 307
#define ID_ANI_PLANT_RIGHT_TOP_SHOOT 308

#define ID_ANI_PLANT_LEFT_UNDER_NOT_SHOOT_GREEN	321
#define ID_ANI_PLANT_LEFT_UNDER_SHOOT_GREEN 322
#define ID_ANI_PLANT_LEFT_TOP_NOT_SHOOT_GREEN 323
#define ID_ANI_PLANT_LEFT_TOP_SHOOT_GREEN 324
#define ID_ANI_PLANT_RIGHT_UNDER_NOT_SHOOT_GREEN 325
#define ID_ANI_PLANT_RIGHT_UNDER_SHOOT_GREEN 326
#define ID_ANI_PLANT_RIGHT_TOP_NOT_SHOOT_GREEN 327
#define ID_ANI_PLANT_RIGHT_TOP_SHOOT_GREEN 328

#define ID_ANI_PLANT_NOT_SHOOT 311
