#pragma once

// bounding box size
#define PLANT_SHOOTER_BBOX_WIDTH 16
#define PLANT_SHOOTER_BBOX_HEIGHT_RED 32
#define PLANT_SHOOTER_BBOX_HEIGHT_GREEN 24

// time out

#define TIME_RELOAD_BULLET 100

// type
#define PLANT_SHOOTER_RED 1
#define PLANT_SHOOTER_GREEN 2

#pragma region ANIMATION

// red plant shooter
// top and under is the position of plant with mario
#define ID_ANI_RED_PLANT_SHOOTER_LEFT_NOT_SHOOT_UNDER 602001
#define ID_ANI_RED_PLANT_SHOOTER_LEFT_SHOOT_UNDER 602002

#define ID_ANI_RED_PLANT_SHOOTER_LEFT_NOT_SHOOT_TOP 602003
#define ID_ANI_RED_PLANT_SHOOTER_LEFT_SHOOT_TOP 602004

#define ID_ANI_RED_PLANT_SHOOTER_RIGHT_NOT_SHOOT_UNDER	602005
#define ID_ANI_RED_PLANT_SHOOTER_RIGHT_SHOOT_UNDER	602006

#define ID_ANI_RED_PLANT_SHOOTER_RIGHT_NOT_SHOOT_TOP 602007
#define ID_ANI_RED_PLANT_SHOOTER_RIGHT_SHOOT_TOP 602008

// green plant shooter

#define ID_ANI_GREEN_PLANT_SHOOTER_LEFT_NOT_SHOOT_UNDER 602011
#define ID_ANI_GREEN_PLANT_SHOOTER_LEFT_SHOOT_UNDER 602012

#define ID_ANI_GREEN_PLANT_SHOOTER_LEFT_NOT_SHOOT_TOP 602013
#define ID_ANI_GREEN_PLANT_SHOOTER_LEFT_SHOOT_TOP 602014

#define ID_ANI_GREEN_PLANT_SHOOTER_RIGHT_NOT_SHOOT_UNDER	602015
#define ID_ANI_GREEN_PLANT_SHOOTER_RIGHT_SHOOT_UNDER	602016

#define ID_ANI_GREEN_PLANT_SHOOTER_RIGHT_NOT_SHOOT_TOP 602017
#define ID_ANI_GREEN_PLANT_SHOOTER_RIGHT_SHOOT_TOP 602018

#pragma endregion