#pragma once

// bounding box size
#define PLANT_SHOOTER_BBOX_WIDTH 16
#define PLANT_SHOOTER_BBOX_HEIGHT 32

// time out

#define TIME_RELOAD_BULLET 100

// type
#define PLANT_SHOOTER_SHOOT_RED 1

#pragma region ANIMATION

// top and under is the position of plant with mario
#define ID_ANI_PLANT_SHOOTER_LEFT_NOT_SHOOT_UNDER 602001
#define ID_ANI_PLANT_SHOOTER_LEFT_SHOOT_UNDER 602002

#define ID_ANI_PLANT_SHOOTER_LEFT_NOT_SHOOT_TOP 602003
#define ID_ANI_PLANT_SHOOTER_LEFT_SHOOT_TOP 602004

#define ID_ANI_PLANT_SHOOTER_RIGHT_NOT_SHOOT_UNDER	602005
#define ID_ANI_PLANT_SHOOTER_RIGHT_SHOOT_UNDER	602006

#define ID_ANI_PLANT_SHOOTER_RIGHT_NOT_SHOOT_TOP 602007
#define ID_ANI_PLANT_SHOOTER_RIGHT_SHOOT_TOP 602008

#pragma endregion