#pragma once

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_DOOR 6
#define OBJECT_TYPE_GRASS 7
#define OBJECT_TYPE_QUESTION_BRICK 8
#define OBJECT_TYPE_PIPE 9
#define OBJECT_TYPE_KOOPA 10
#define OBJECT_TYPE_PLANT 11

#define OBJECT_TYPE_PORTAL	50
