#pragma once

#define OBJECT_TYPE_MARIO	0

// monsters
#define OBJECT_TYPE_GOOMBA	1
#define OBJECT_TYPE_KOOPA 2
#define OBJECT_TYPE_PLANT 3

// platforms
#define OBJECT_TYPE_PLATFORM 5

// items
#define OBJECT_TYPE_COIN 10
#define OBJECT_TYPE_PIPE 11

// materials
#define OBJECT_TYPE_PORTAL	50
#define OBJECT_TYPE_DOOR 51

#define OBJECT_TYPE_BREAKABLE_BRICK	60
#define OBJECT_TYPE_QUESTION_BRICK 61
#define OBJECT_TYPE_GRASS 62